name: Run JMeter Test using PerfAction

on: [push]

jobs:
  run-jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: PerfAction for JMeter
        uses: QAInsights/PerfAction@v5.6.3
        with:
          test-plan-path: './tests/Petstore_June_02.jmx'
          results-file: 'results.jtl'
          args: '-Jthreads=10 -Jduration=60'

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-results
          path: results.jtl
